// <auto-generated />
using System;
using BookStoreServer.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreServer.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231011150632_mg4")]
    partial class mg4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreServer.WebApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1699),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1704),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1707),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1709),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1712),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1715),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1718),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1720),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1722),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1726),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1728),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1731),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1733),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1735),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1738),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1740),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1742),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1746),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1748),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1750),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Author 21",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1753),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Author 22",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1755),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Author 23",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1757),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Author 24",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1759),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Author 25",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1762),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Author 26",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1765),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Author 27",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1767),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Author 28",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1769),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Author 29",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1772),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Author 30",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1774),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Author 31",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1776),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 31"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Author 32",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1778),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 32"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Author 33",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1781),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Author 34",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1784),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 34"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Author 35",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1831),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 35"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Author 36",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1833),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 36"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Author 37",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1835),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Author 38",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1838),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 38"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Author 39",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1840),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 39"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Author 40",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1842),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 40"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Author 41",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1844),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Author 42",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1847),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 42"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Author 43",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1849),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 43"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Author 44",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1851),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 44"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Author 45",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1853),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Author 46",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1856),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 46"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Author 47",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1858),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 47"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Author 48",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1860),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 48"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Author 49",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1863),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 49"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Author 50",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1865),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 50"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Author 51",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1867),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 51"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Author 52",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1869),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 52"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Author 53",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1872),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 53"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Author 54",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1874),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 54"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Author 55",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1876),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 55"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Author 56",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1878),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 56"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Author 57",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1881),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 57"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Author 58",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1883),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 58"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Author 59",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1885),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 59"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Author 60",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1888),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 60"
                        },
                        new
                        {
                            Id = 61,
                            Author = "Author 61",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1890),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 61"
                        },
                        new
                        {
                            Id = 62,
                            Author = "Author 62",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1892),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 62"
                        },
                        new
                        {
                            Id = 63,
                            Author = "Author 63",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1894),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 63"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Author 64",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1897),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 64"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Author 65",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1899),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 65"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Author 66",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1902),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 66"
                        },
                        new
                        {
                            Id = 67,
                            Author = "Author 67",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1905),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 67"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Author 68",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1907),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 68"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Author 69",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1951),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 69"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Author 70",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1953),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 70"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Author 71",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1955),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 71"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Author 72",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1958),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 72"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Author 73",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1960),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 73"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Author 74",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1962),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 74"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Author 75",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1964),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 75"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Author 76",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1967),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 76"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Author 77",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1969),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 77"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Author 78",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1971),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 78"
                        },
                        new
                        {
                            Id = 79,
                            Author = "Author 79",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1973),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 79"
                        },
                        new
                        {
                            Id = 80,
                            Author = "Author 80",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1976),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 80"
                        },
                        new
                        {
                            Id = 81,
                            Author = "Author 81",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1978),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 81"
                        },
                        new
                        {
                            Id = 82,
                            Author = "Author 82",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1981),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 82"
                        },
                        new
                        {
                            Id = 83,
                            Author = "Author 83",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1983),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 83"
                        },
                        new
                        {
                            Id = 84,
                            Author = "Author 84",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1986),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 84"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Author 85",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1988),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 85"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Author 86",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1990),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 86"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Author 87",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1992),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 87"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Author 88",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1995),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 88"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Author 89",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1997),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 89"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Author 90",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(1999),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 90"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Author 91",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2002),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 91"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Author 92",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2004),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 92"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Author 93",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2006),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 93"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Author 94",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2008),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 94"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Author 95",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2011),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 95"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Author 96",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2013),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 96"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Author 97",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2015),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 97"
                        },
                        new
                        {
                            Id = 98,
                            Author = "Author 98",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2017),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 98"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Author 99",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2020),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 99"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Author 100",
                            CoverImageUrl = "https://m.media-amazon.com/images/I/715dYvRM3lL._AC_UF1000,1000_QL80_.jpg",
                            CreateAt = new DateTime(2023, 10, 11, 18, 6, 31, 762, DateTimeKind.Local).AddTicks(2023),
                            ISBN = "978-0321125217",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 10m,
                            Quantity = 10,
                            Summary = "",
                            Title = "Book 100"
                        });
                });

            modelBuilder.Entity("BookStoreServer.WebApi.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 21,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 22,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 23,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 24,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 25,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 26,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 27,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 28,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 29,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 30,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 31,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 32,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 33,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 34,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 35,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 36,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 37,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 38,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 39,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 40,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 41,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 42,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 43,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 44,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 45,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 46,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 47,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 48,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 49,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 50,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 51,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 52,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 53,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 54,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 55,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 56,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 57,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 58,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 59,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 60,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 61,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 62,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 63,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 64,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 65,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 66,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 67,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 68,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 69,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 70,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 71,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 72,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 73,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 74,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 75,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 76,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 77,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 78,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 79,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 80,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 81,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 82,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 83,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 84,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 85,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 86,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 87,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 88,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 89,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 90,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 91,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 92,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 93,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 94,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 95,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 96,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 97,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 98,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 99,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 100,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("BookStoreServer.WebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category3"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category4"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category5"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category6"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category7"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category8"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category9"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category10"
                        });
                });

            modelBuilder.Entity("BookStoreServer.WebApi.Models.BookCategory", b =>
                {
                    b.HasOne("BookStoreServer.WebApi.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreServer.WebApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
